# Generated by Django 2.2.5 on 2019-09-20 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_group_numbers', models.CharField(max_length=100)),
                ('topic', models.CharField(max_length=100)),
            ],
        ),
    ]
