# Generated by Django 2.2.5 on 2019-11-02 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100)),
                ('video_url', models.CharField(max_length=100)),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('description', models.CharField(max_length=1000)),
                ('team_group_number_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first', to='Teams.Teams')),
                ('team_group_number_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second', to='Teams.Teams')),
            ],
        ),
    ]
