# Generated by Django 2.2.5 on 2019-11-02 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Skits', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skits',
            old_name='image',
            new_name='image_1',
        ),
        migrations.AddField(
            model_name='skits',
            name='image_2',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
        migrations.AddField(
            model_name='skits',
            name='image_3',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='skits',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
