# Generated by Django 2.2.5 on 2019-09-22 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Skits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skits',
            name='video_url',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
