# Generated by Django 2.1.3 on 2019-10-29 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Teams', '0001_initial'),
        ('Skits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skits',
            name='team_group_numbers1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='second', to='Teams.Teams'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='skits',
            name='team_group_numbers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first', to='Teams.Teams'),
        ),
    ]
