# Generated by Django 2.1.3 on 2019-09-25 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Skits', '0002_skits_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='skits',
            name='image',
            field=models.ImageField(default=1, upload_to='profile_pics'),
            preserve_default=False,
        ),
    ]
