# Generated by Django 2.1.3 on 2019-10-29 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Skits', '0002_auto_20191029_1550'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skits',
            old_name='team_group_numbers',
            new_name='team_group_number_1',
        ),
        migrations.RenameField(
            model_name='skits',
            old_name='team_group_numbers1',
            new_name='team_group_number_2',
        ),
    ]
