# Generated by Django 2.1.3 on 2019-11-01 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Skits', '0003_auto_20191029_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='skits',
            name='description',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
