# Generated by Django 2.1.3 on 2019-09-25 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Skits', '0003_skits_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skits',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
