# Generated by Django 2.1.3 on 2019-09-25 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Skits', '0004_auto_20190925_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skits',
            name='image',
            field=models.FileField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
