# Generated by Django 2.1.3 on 2019-10-12 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Skits', '0005_auto_20190925_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='skits',
            name='file',
            field=models.FileField(default='default.jpg', upload_to='files'),
        ),
        migrations.AlterField(
            model_name='skits',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
