# Generated by Django 2.2.5 on 2019-09-25 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_number', models.CharField(max_length=100)),
                ('member_1', models.CharField(max_length=100)),
                ('member_2', models.CharField(blank=True, max_length=100)),
                ('member_3', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
