# Generated by Django 2.2.5 on 2019-11-02 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_number', models.CharField(max_length=100)),
                ('member_1_name', models.CharField(max_length=100)),
                ('member_1_usn', models.CharField(max_length=100)),
                ('member_2_name', models.CharField(blank=True, max_length=100)),
                ('member_2_usn', models.CharField(blank=True, max_length=100)),
                ('member_3_name', models.CharField(blank=True, max_length=100)),
                ('member_3_usn', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
