# Generated by Django 2.1.3 on 2019-10-29 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='team_number',
            field=models.IntegerField(),
        ),
    ]
