# Generated by Django 2.2.5 on 2019-11-02 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Teams', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teams',
            old_name='member_1_name',
            new_name='member_1',
        ),
        migrations.RenameField(
            model_name='teams',
            old_name='member_2_name',
            new_name='member_2',
        ),
        migrations.RenameField(
            model_name='teams',
            old_name='member_3_name',
            new_name='member_3',
        ),
    ]
