# Generated by Django 2.1.3 on 2019-11-13 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='group_photo',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
