# Generated by Django 2.2.5 on 2019-11-02 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Teams', '0002_auto_20191102_1030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teams',
            old_name='member_1_usn',
            new_name='member_1_USN',
        ),
        migrations.RenameField(
            model_name='teams',
            old_name='member_2_usn',
            new_name='member_2_USN',
        ),
        migrations.RenameField(
            model_name='teams',
            old_name='member_3_usn',
            new_name='member_3_USN',
        ),
    ]
