# Generated by Django 2.2.7 on 2019-11-19 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teams', '0002_teams_group_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='group_photo',
            field=models.ImageField(default='default.jpg', height_field=100, upload_to='profile_pics', width_field=100),
        ),
    ]
