# Generated by Django 2.1.3 on 2019-10-29 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teams', '0002_auto_20191029_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='team_number',
            field=models.CharField(max_length=100),
        ),
    ]
