# Generated by Django 2.1.3 on 2019-10-29 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teams', '0004_auto_20191029_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='member_3_usn',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
