# Generated by Django 2.2.7 on 2019-11-09 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presentations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100)),
                ('image_1', models.FileField(blank=True, upload_to='')),
                ('image_2', models.FileField(blank=True, upload_to='')),
                ('image_3', models.FileField(blank=True, upload_to='')),
                ('description', models.TextField(max_length=1000)),
                ('team_group_numbers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teams.Teams')),
            ],
        ),
    ]
