# Generated by Django 2.2.5 on 2019-11-02 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Presentations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='presentations',
            old_name='file',
            new_name='image_1',
        ),
        migrations.AddField(
            model_name='presentations',
            name='image_2',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='presentations',
            name='image_3',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
