# Generated by Django 2.2.7 on 2019-11-18 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Presentations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentations',
            name='file',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
