# Generated by Django 2.2.7 on 2019-11-19 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Presentations', '0002_presentations_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentations',
            name='description',
            field=models.TextField(help_text="Please don't exceed 450 characters.", max_length=1000),
        ),
        migrations.AlterField(
            model_name='presentations',
            name='team_group_numbers',
            field=models.ForeignKey(help_text='Please add your team first if not yet done.', on_delete=django.db.models.deletion.CASCADE, to='Teams.Teams'),
        ),
    ]
