# Generated by Django 2.2.5 on 2019-09-25 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Presentations', '0002_presentations_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentations',
            name='team_group_numbers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teams.Teams'),
        ),
    ]
