# Generated by Django 2.2.5 on 2019-11-02 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Presentations', '0002_auto_20191102_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentations',
            name='description',
            field=models.TextField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
