# Generated by Django 2.2.5 on 2019-09-25 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Presentations', '0003_auto_20190926_0402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentations',
            name='team_group_numbers',
            field=models.CharField(max_length=100),
        ),
    ]
